name: Flutter - Continuous Delivery

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions: {}

env:
  DEBUG: true
  PROJECT_NAME: testing
  SERVICE_NAME: voting
  BRANCH: ${{ contains('main staging', github.ref_name) && github.ref_name || 'dev' }}
  FLUTTER_VERSION: "stable"
  JAVA_VERSION: "17"

jobs:
  android_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: true

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Prepare Android keystore and key.properties
        shell: bash
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/app/upload-keystore.jks
          cat > android/key.properties <<'EOF'
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Fastlane deploy (Play Internal)
        env:
          PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
        run: |
          cd android
          fastlane android deploy

      - name: Upload AAB artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/*.aab
